---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a bucket to store uploaded files"

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  FrontendDomain:
    Type: String
  BackendDomain:
    Type: String

Resources:
  VideoUploads:
    Type: "AWS::S3::Bucket"
    Properties:
      AccelerateConfiguration:
        AccelerationStatus: "Enabled"
      AccessControl: "Private"
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 2
          Status: "Enabled"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods:
            - "HEAD"
            - "GET"
            - "PUT"
            - "POST"
            AllowedOrigins: ["*"]
            ExposedHeaders:
            - "etag"
  
  FrontendWebsite:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
  
  FrontendWebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref "FrontendWebsite"
      PolicyDocument:
        "Version": "2012-10-17"
        "Statement":
        - "Effect": "Allow"
          "Principal": "*"
          "Action":
          - "s3:GetObject"
          "Resource":
          - !Sub "arn:aws:s3:::${FrontendWebsite}/*"
  
  FrontendWebsiteCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Sub "${FrontendDomain}"
      DomainValidationOptions:
        - DomainName: !Sub "${FrontendDomain}"
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "${BackendDomain}"
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
      - !Sub "${BackendDomain}"
      ValidationMethod: "DNS"

Outputs:
  AcceleratedEndpoint:
    Value: !Sub "${VideoUploads}.s3-accelerate.amazonaws.com"
  FrontendURL:
    Value: !GetAtt "FrontendWebsite.WebsiteURL"