name: Presenter Portal

on:
  push:
    branches:
      - main

jobs:
  deploy-backend-bucket:
    name: Deploy backend-bucket.cfn.yaml
    runs-on: ubuntu-latest

    outputs:
      backendBucket: ${{ steps.step1.deploy-bucket.outputs.backendBucket }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2 # default
        verbose: false # default
        
    - name: Deploy backend-bucket.cfn.yaml
      id: deploy-bucket
      run: |
        ./deploy-bucket.cfn.yaml.sh

  build-backend-lambda:
    name: Build backend-lambda and push to S3
    runs-on: ubuntu-latest

    needs: deploy-backend-bucket

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2 # default
        verbose: false # default

    - name: Build and push to S3
      env:
        LAMBDA_BUCKET: ${{needs.deploy-backend-bucket.outputs.backendBucket}}
      run: |
        ./backend-lambda/ci/pr.sh
